/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// API_Entities_Deployments_Approval model
type ApiEntitiesDeploymentsApproval struct {
	User      *ApiEntitiesUserBasic `json:"user,omitempty"`
	Status    string                `json:"status,omitempty"`
	CreatedAt time.Time             `json:"created_at,omitempty"`
	Comment   string                `json:"comment,omitempty"`
}
