/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// API_Entities_ProjectGroupLink model
type ApiEntitiesProjectGroupLink struct {
	Id          int32  `json:"id,omitempty"`
	ProjectId   int32  `json:"project_id,omitempty"`
	GroupId     int32  `json:"group_id,omitempty"`
	GroupAccess int32  `json:"group_access,omitempty"`
	ExpiresAt   string `json:"expires_at,omitempty"`
}
