/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiEntitiesProjectImportFailedRelation struct {
	Id               string    `json:"id,omitempty"`
	CreatedAt        time.Time `json:"created_at,omitempty"`
	ExceptionClass   string    `json:"exception_class,omitempty"`
	Source           string    `json:"source,omitempty"`
	ExceptionMessage string    `json:"exception_message,omitempty"`
	RelationName     string    `json:"relation_name,omitempty"`
	LineNumber       int32     `json:"line_number,omitempty"`
}
