/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// API_Entities_Ci_Job model
type ApiEntitiesCiJob struct {
	Id           int32     `json:"id,omitempty"`
	Status       string    `json:"status,omitempty"`
	Stage        string    `json:"stage,omitempty"`
	Name         string    `json:"name,omitempty"`
	Ref          string    `json:"ref,omitempty"`
	Tag          bool      `json:"tag,omitempty"`
	Coverage     float32   `json:"coverage,omitempty"`
	AllowFailure bool      `json:"allow_failure,omitempty"`
	CreatedAt    time.Time `json:"created_at,omitempty"`
	StartedAt    time.Time `json:"started_at,omitempty"`
	FinishedAt   time.Time `json:"finished_at,omitempty"`
	ErasedAt     time.Time `json:"erased_at,omitempty"`
	// Time spent running
	Duration float32 `json:"duration,omitempty"`
	// Time spent enqueued
	QueuedDuration    float32                       `json:"queued_duration,omitempty"`
	User              *ApiEntitiesUser              `json:"user,omitempty"`
	Commit            *ApiEntitiesCommit            `json:"commit,omitempty"`
	Pipeline          *ApiEntitiesCiPipelineBasic   `json:"pipeline,omitempty"`
	FailureReason     string                        `json:"failure_reason,omitempty"`
	WebUrl            string                        `json:"web_url,omitempty"`
	Project           *ApiEntitiesCiJobProject      `json:"project,omitempty"`
	ArtifactsFile     *ApiEntitiesCiJobArtifactFile `json:"artifacts_file,omitempty"`
	Artifacts         []ApiEntitiesCiJobArtifact    `json:"artifacts,omitempty"`
	Runner            *ApiEntitiesCiRunner          `json:"runner,omitempty"`
	RunnerManager     *ApiEntitiesCiRunnerManager   `json:"runner_manager,omitempty"`
	ArtifactsExpireAt time.Time                     `json:"artifacts_expire_at,omitempty"`
	Archived          bool                          `json:"archived,omitempty"`
	TagList           []string                      `json:"tag_list,omitempty"`
}
