/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// API_Entities_Suggestion model
type ApiEntitiesSuggestion struct {
	Id          string `json:"id,omitempty"`
	FromLine    string `json:"from_line,omitempty"`
	ToLine      string `json:"to_line,omitempty"`
	Appliable   string `json:"appliable,omitempty"`
	Applied     string `json:"applied,omitempty"`
	FromContent string `json:"from_content,omitempty"`
	ToContent   string `json:"to_content,omitempty"`
}
