/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Build log state
type PutApiV4JobsIdOutput struct {
	// Job's trace CRC32 checksum
	Checksum string `json:"checksum,omitempty"`
	// Job's trace size in bytes
	Bytesize int32 `json:"bytesize,omitempty"`
}
