/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Create a feature flag user list
type PostApiV4ProjectsIdFeatureFlagsUserLists struct {
	// The name of the list
	Name string `json:"name"`
	// A comma separated list of external user ids
	UserXids string `json:"user_xids"`
}
