/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// API_Entities_DeploymentExtended model
type ApiEntitiesDeploymentExtended struct {
	Id                   int32                                  `json:"id,omitempty"`
	Iid                  int32                                  `json:"iid,omitempty"`
	Ref                  string                                 `json:"ref,omitempty"`
	Sha                  string                                 `json:"sha,omitempty"`
	CreatedAt            time.Time                              `json:"created_at,omitempty"`
	UpdatedAt            time.Time                              `json:"updated_at,omitempty"`
	User                 *ApiEntitiesUserBasic                  `json:"user,omitempty"`
	Environment          *ApiEntitiesEnvironmentBasic           `json:"environment,omitempty"`
	Deployable           *ApiEntitiesCiJob                      `json:"deployable,omitempty"`
	Status               string                                 `json:"status,omitempty"`
	PendingApprovalCount int32                                  `json:"pending_approval_count,omitempty"`
	Approvals            *ApiEntitiesDeploymentsApproval        `json:"approvals,omitempty"`
	ApprovalSummary      *ApiEntitiesDeploymentsApprovalSummary `json:"approval_summary,omitempty"`
}
