/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// API_Entities_DraftNote model
type ApiEntitiesDraftNote struct {
	Id                int32       `json:"id,omitempty"`
	AuthorId          int32       `json:"author_id,omitempty"`
	MergeRequestId    int32       `json:"merge_request_id,omitempty"`
	ResolveDiscussion bool        `json:"resolve_discussion,omitempty"`
	DiscussionId      int32       `json:"discussion_id,omitempty"`
	Note              string      `json:"note,omitempty"`
	CommitId          int32       `json:"commit_id,omitempty"`
	LineCode          string      `json:"line_code,omitempty"`
	Position          interface{} `json:"position,omitempty"`
}
