/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiEntitiesProtectedEnvironmentsApprovalRuleForSummary struct {
	Id                     string                          `json:"id,omitempty"`
	UserId                 string                          `json:"user_id,omitempty"`
	GroupId                string                          `json:"group_id,omitempty"`
	AccessLevel            string                          `json:"access_level,omitempty"`
	AccessLevelDescription string                          `json:"access_level_description,omitempty"`
	RequiredApprovals      string                          `json:"required_approvals,omitempty"`
	GroupInheritanceType   string                          `json:"group_inheritance_type,omitempty"`
	DeploymentApprovals    *ApiEntitiesDeploymentsApproval `json:"deployment_approvals,omitempty"`
}
