/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Create a new environment
type PostApiV4ProjectsIdEnvironments struct {
	// The name of the environment
	Name string `json:"name"`
	// Place to link to for this environment
	ExternalUrl string `json:"external_url,omitempty"`
	// The tier of the new environment. Allowed values are `production`, `staging`, `testing`, `development`, and `other`
	Tier string `json:"tier,omitempty"`
}
