/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PostApiV4ProjectsIdReleasesAssets struct {
	Links []PostApiV4ProjectsIdReleasesAssetsLinks `json:"links,omitempty"`
}
