/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Edit project hook
type PutApiV4ProjectsIdHooksHookId struct {
	// The URL to send the request to
	Url string `json:"url,omitempty"`
	// Name of the hook
	Name string `json:"name,omitempty"`
	// Description of the hook
	Description string `json:"description,omitempty"`
	// Trigger hook on push events
	PushEvents bool `json:"push_events,omitempty"`
	// Trigger hook on issues events
	IssuesEvents bool `json:"issues_events,omitempty"`
	// Trigger hook on confidential issues events
	ConfidentialIssuesEvents bool `json:"confidential_issues_events,omitempty"`
	// Trigger hook on merge request events
	MergeRequestsEvents bool `json:"merge_requests_events,omitempty"`
	// Trigger hook on tag push events
	TagPushEvents bool `json:"tag_push_events,omitempty"`
	// Trigger hook on note (comment) events
	NoteEvents bool `json:"note_events,omitempty"`
	// Trigger hook on confidential note (comment) events
	ConfidentialNoteEvents bool `json:"confidential_note_events,omitempty"`
	// Trigger hook on job events
	JobEvents bool `json:"job_events,omitempty"`
	// Trigger hook on pipeline events
	PipelineEvents bool `json:"pipeline_events,omitempty"`
	// Trigger hook on wiki events
	WikiPageEvents bool `json:"wiki_page_events,omitempty"`
	// Trigger hook on deployment events
	DeploymentEvents bool `json:"deployment_events,omitempty"`
	// Trigger hook on release events
	ReleasesEvents bool `json:"releases_events,omitempty"`
	// Trigger hook on emoji events
	EmojiEvents bool `json:"emoji_events,omitempty"`
	// Trigger hook on project access token expiry events
	ResourceAccessTokenEvents bool `json:"resource_access_token_events,omitempty"`
	// Do SSL verification when triggering the hook
	EnableSslVerification bool `json:"enable_ssl_verification,omitempty"`
	// Secret token to validate received payloads; this will not be returned in the response
	Token string `json:"token,omitempty"`
	// Trigger hook on specified branch only
	PushEventsBranchFilter string `json:"push_events_branch_filter,omitempty"`
	// Custom template for the request payload
	CustomWebhookTemplate string `json:"custom_webhook_template,omitempty"`
	// URL variables for interpolation
	UrlVariables []PostApiV4ProjectsIdHooksUrlVariables `json:"url_variables,omitempty"`
}
