/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// Update a user's credit_card_validation
type PutApiV4UserUserIdCreditCardValidation struct {
	// The time when the user's credit card was validated
	CreditCardValidatedAt time.Time `json:"credit_card_validated_at"`
	// The month the credit card expires
	CreditCardExpirationMonth int32 `json:"credit_card_expiration_month"`
	// The year the credit card expires
	CreditCardExpirationYear int32 `json:"credit_card_expiration_year"`
	// The credit card holder name
	CreditCardHolderName string `json:"credit_card_holder_name"`
	// The last 4 digits of credit card number
	CreditCardMaskNumber string `json:"credit_card_mask_number"`
	// The credit card network name
	CreditCardType string `json:"credit_card_type"`
	// The Zuora payment method ID
	ZuoraPaymentMethodXid string `json:"zuora_payment_method_xid,omitempty"`
}
