/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"os"
)

// Create a secure file
type PostApiV4ProjectsIdSecureFiles struct {
	// The name of the file being uploaded. The filename must be unique within             the project
	Name string `json:"name"`
	// The secure file being uploaded
	File **os.File `json:"file"`
}
