/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type EeApiEntitiesGeoNodeStatusLinks struct {
	Self string `json:"self,omitempty"`
	Node string `json:"node,omitempty"`
}
