/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiEntitiesProjectLinks struct {
	Self          string `json:"self,omitempty"`
	Issues        string `json:"issues,omitempty"`
	MergeRequests string `json:"merge_requests,omitempty"`
	RepoBranches  string `json:"repo_branches,omitempty"`
	Labels        string `json:"labels,omitempty"`
	Events        string `json:"events,omitempty"`
	Members       string `json:"members,omitempty"`
	ClusterAgents string `json:"cluster_agents,omitempty"`
}
