/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Responsible for making HTTP POST /repo.git/info/refs?service=git-receive-pack                   request from secondary gitlab-shell to primary
type PostApiV4GeoProxyGitSshReceivePack struct {
	SecretToken string                                 `json:"secret_token"`
	Data        *PostApiV4GeoProxyGitSshUploadPackData `json:"data"`
	// Output from git-receive-pack
	Output string `json:"output"`
}
