/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// API_Entities_DeployKey model
type ApiEntitiesDeployKey struct {
	Id                         int32                       `json:"id,omitempty"`
	Title                      string                      `json:"title,omitempty"`
	CreatedAt                  time.Time                   `json:"created_at,omitempty"`
	ExpiresAt                  time.Time                   `json:"expires_at,omitempty"`
	Key                        string                      `json:"key,omitempty"`
	UsageType                  string                      `json:"usage_type,omitempty"`
	Fingerprint                string                      `json:"fingerprint,omitempty"`
	FingerprintSha256          string                      `json:"fingerprint_sha256,omitempty"`
	ProjectsWithWriteAccess    *ApiEntitiesProjectIdentity `json:"projects_with_write_access,omitempty"`
	ProjectsWithReadonlyAccess *ApiEntitiesProjectIdentity `json:"projects_with_readonly_access,omitempty"`
}
