/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// API_Entities_Packages_Debian_Distribution model
type ApiEntitiesPackagesDebianDistribution struct {
	Id                       int32    `json:"id,omitempty"`
	Codename                 string   `json:"codename,omitempty"`
	Suite                    string   `json:"suite,omitempty"`
	Origin                   string   `json:"origin,omitempty"`
	Label                    string   `json:"label,omitempty"`
	Version                  string   `json:"version,omitempty"`
	Description              string   `json:"description,omitempty"`
	ValidTimeDurationSeconds int32    `json:"valid_time_duration_seconds,omitempty"`
	Components               []string `json:"components,omitempty"`
	Architectures            []string `json:"architectures,omitempty"`
}
