/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// API_Entities_UserCounts model
type ApiEntitiesUserCounts struct {
	MergeRequests                int32 `json:"merge_requests,omitempty"`
	AssignedIssues               int32 `json:"assigned_issues,omitempty"`
	AssignedMergeRequests        int32 `json:"assigned_merge_requests,omitempty"`
	ReviewRequestedMergeRequests int32 `json:"review_requested_merge_requests,omitempty"`
	Todos                        int32 `json:"todos,omitempty"`
}
