/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Create a trigger token
type PostApiV4ProjectsIdTriggers struct {
	// The trigger token description
	Description string `json:"description"`
}
