/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameStrategies struct {
	// The feature flag strategy ID
	Id int32 `json:"id,omitempty"`
	// The strategy name
	Name string `json:"name,omitempty"`
	// The strategy parameters as a JSON-formatted string e.g. `{\"userIds\":\"user1\"}`
	Parameters string `json:"parameters,omitempty"`
	// The ID of the feature flag user list
	UserListId int32 `json:"user_list_id,omitempty"`
	// Delete the strategy when true
	Destroy bool                                                  `json:"_destroy,omitempty"`
	Scopes  []PutApiV4ProjectsIdFeatureFlagsFeatureFlagNameScopes `json:"scopes,omitempty"`
}
