/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Create/Edit Telegram integration
type PutApiV4ProjectsIdIntegrationsTelegram struct {
	// Custom hostname of the Telegram API. The default value is `https://api.telegram.org`.
	Hostname string `json:"hostname,omitempty"`
	// The Telegram chat token. For example, 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11
	Token string `json:"token"`
	// Unique identifier for the target chat or username of the target channel (in the format @channelusername)
	Room string `json:"room"`
	// Unique identifier for the target message thread (topic in a forum supergroup)
	Thread int32 `json:"thread,omitempty"`
	// Branches for which notifications are to be sent.
	BranchesToBeNotified string `json:"branches_to_be_notified,omitempty"`
	// Send notifications for broken pipelines
	NotifyOnlyBrokenPipelines bool `json:"notify_only_broken_pipelines,omitempty"`
	// Trigger event for pushes to the repository.
	PushEvents bool `json:"push_events,omitempty"`
	// Trigger event when an issue is created, updated, or closed.
	IssuesEvents bool `json:"issues_events,omitempty"`
	// Trigger event when a confidential issue is created, updated, or closed.
	ConfidentialIssuesEvents bool `json:"confidential_issues_events,omitempty"`
	// Trigger event when a merge request is created, updated, or merged.
	MergeRequestsEvents bool `json:"merge_requests_events,omitempty"`
	// Trigger event for new comments.
	NoteEvents bool `json:"note_events,omitempty"`
	// Trigger event for new comments on confidential issues.
	ConfidentialNoteEvents bool `json:"confidential_note_events,omitempty"`
	// Trigger event for new tags pushed to the repository.
	TagPushEvents bool `json:"tag_push_events,omitempty"`
	// Trigger event when a pipeline status changes.
	PipelineEvents bool `json:"pipeline_events,omitempty"`
	// Trigger event when a wiki page is created or updated.
	WikiPageEvents bool `json:"wiki_page_events,omitempty"`
	// Trigger event when an incident is created.
	IncidentEvents      bool `json:"incident_events,omitempty"`
	VulnerabilityEvents bool `json:"vulnerability_events,omitempty"`
}
