/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Updates pipeline metadata
type PutApiV4ProjectsIdPipelinesPipelineIdMetadata struct {
	// The name of the pipeline
	Name string `json:"name"`
}
