/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// API_Entities_MRNote model
type ApiEntitiesMrNote struct {
	Note   string                `json:"note,omitempty"`
	Author *ApiEntitiesUserBasic `json:"author,omitempty"`
}
