/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// API_Entities_ProjectRepositoryStorage model
type ApiEntitiesProjectRepositoryStorage struct {
	DiskPath          string    `json:"disk_path,omitempty"`
	ProjectId         int32     `json:"project_id,omitempty"`
	RepositoryStorage string    `json:"repository_storage,omitempty"`
	CreatedAt         time.Time `json:"created_at,omitempty"`
}
