/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Multi-line start and end
type PostApiV4ProjectsIdMergeRequestsMergeRequestIidDraftNotesPositionLineRange struct {
	Start *PostApiV4ProjectsIdMergeRequestsMergeRequestIidDraftNotesPositionLineRangeStart `json:"start,omitempty"`
	End   *PostApiV4ProjectsIdMergeRequestsMergeRequestIidDraftNotesPositionLineRangeEnd   `json:"end,omitempty"`
}
