/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// API_Entities_Dictionary_Table model
type ApiEntitiesDictionaryTable struct {
	TableName         string   `json:"table_name,omitempty"`
	FeatureCategories []string `json:"feature_categories,omitempty"`
}
