/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Create a new draft note
type PostApiV4ProjectsIdMergeRequestsMergeRequestIidDraftNotes struct {
	// The content of a note.
	Note string `json:"note"`
	// The ID of a discussion the draft note replies to.
	InReplyToDiscussionId string `json:"in_reply_to_discussion_id,omitempty"`
	// The sha of a commit to associate the draft note to.
	CommitId string `json:"commit_id,omitempty"`
	// The associated discussion should be resolved.
	ResolveDiscussion bool                                                               `json:"resolve_discussion,omitempty"`
	Position          *PostApiV4ProjectsIdMergeRequestsMergeRequestIidDraftNotesPosition `json:"position,omitempty"`
}
