/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// API_Entities_RelatedIssue model
type ApiEntitiesRelatedIssue struct {
	Id          int32                 `json:"id,omitempty"`
	Iid         int32                 `json:"iid,omitempty"`
	ProjectId   int32                 `json:"project_id,omitempty"`
	Title       string                `json:"title,omitempty"`
	Description string                `json:"description,omitempty"`
	State       string                `json:"state,omitempty"`
	CreatedAt   time.Time             `json:"created_at,omitempty"`
	UpdatedAt   time.Time             `json:"updated_at,omitempty"`
	ClosedAt    time.Time             `json:"closed_at,omitempty"`
	ClosedBy    *ApiEntitiesUserBasic `json:"closed_by,omitempty"`
	Labels      []string              `json:"labels,omitempty"`
	Milestone   *ApiEntitiesMilestone `json:"milestone,omitempty"`
	Assignees   *ApiEntitiesUserBasic `json:"assignees,omitempty"`
	Author      *ApiEntitiesUserBasic `json:"author,omitempty"`
	// One of [\"ISSUE\", \"INCIDENT\", \"TEST_CASE\", \"REQUIREMENT\", \"TASK\"]
	Type_                string                         `json:"type,omitempty"`
	Assignee             *ApiEntitiesUserBasic          `json:"assignee,omitempty"`
	UserNotesCount       string                         `json:"user_notes_count,omitempty"`
	MergeRequestsCount   string                         `json:"merge_requests_count,omitempty"`
	Upvotes              string                         `json:"upvotes,omitempty"`
	Downvotes            string                         `json:"downvotes,omitempty"`
	DueDate              string                         `json:"due_date,omitempty"`
	Confidential         bool                           `json:"confidential,omitempty"`
	DiscussionLocked     bool                           `json:"discussion_locked,omitempty"`
	IssueType            string                         `json:"issue_type,omitempty"`
	WebUrl               string                         `json:"web_url,omitempty"`
	TimeStats            *ApiEntitiesIssuableTimeStats  `json:"time_stats,omitempty"`
	TaskCompletionStatus string                         `json:"task_completion_status,omitempty"`
	Weight               string                         `json:"weight,omitempty"`
	BlockingIssuesCount  string                         `json:"blocking_issues_count,omitempty"`
	HasTasks             string                         `json:"has_tasks,omitempty"`
	TaskStatus           string                         `json:"task_status,omitempty"`
	Links                *ApiEntitiesRelatedIssueLinks  `json:"_links,omitempty"`
	References           *ApiEntitiesIssuableReferences `json:"references,omitempty"`
	// One of [\"UNKNOWN\", \"LOW\", \"MEDIUM\", \"HIGH\", \"CRITICAL\"]
	Severity           string                `json:"severity,omitempty"`
	Subscribed         string                `json:"subscribed,omitempty"`
	MovedToId          string                `json:"moved_to_id,omitempty"`
	Imported           string                `json:"imported,omitempty"`
	ImportedFrom       string                `json:"imported_from,omitempty"`
	ServiceDeskReplyTo string                `json:"service_desk_reply_to,omitempty"`
	EpicIid            string                `json:"epic_iid,omitempty"`
	Epic               *EpicBaseEntity       `json:"epic,omitempty"`
	Iteration          *ApiEntitiesIteration `json:"iteration,omitempty"`
	HealthStatus       string                `json:"health_status,omitempty"`
	IssueLinkId        string                `json:"issue_link_id,omitempty"`
	LinkType           string                `json:"link_type,omitempty"`
	LinkCreatedAt      string                `json:"link_created_at,omitempty"`
	LinkUpdatedAt      string                `json:"link_updated_at,omitempty"`
}
