/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Update the current user's preferences
type PutApiV4UserPreferences struct {
	// Flag indicating the user sees only one file diff per page
	ViewDiffsFileByFile bool `json:"view_diffs_file_by_file,omitempty"`
	// Flag indicating the user sees whitespace changes in diffs
	ShowWhitespaceInDiffs bool `json:"show_whitespace_in_diffs,omitempty"`
	// Flag indicating the user passes their external identities to a CI job as part of a JSON web token.
	PassUserIdentitiesToCiJwt bool `json:"pass_user_identities_to_ci_jwt,omitempty"`
}
