/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// API_Entities_DeployTokenWithToken model
type ApiEntitiesDeployTokenWithToken struct {
	Id        int32     `json:"id,omitempty"`
	Name      string    `json:"name,omitempty"`
	Username  string    `json:"username,omitempty"`
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	Scopes    []string  `json:"scopes,omitempty"`
	Revoked   bool      `json:"revoked,omitempty"`
	Expired   bool      `json:"expired,omitempty"`
	Token     string    `json:"token,omitempty"`
}
