/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// API_Entities_Ci_ResourceGroup model
type ApiEntitiesCiResourceGroup struct {
	Id          int32     `json:"id,omitempty"`
	Key         string    `json:"key,omitempty"`
	ProcessMode string    `json:"process_mode,omitempty"`
	CreatedAt   time.Time `json:"created_at,omitempty"`
	UpdatedAt   time.Time `json:"updated_at,omitempty"`
}
