/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// API_Entities_User model
type ApiEntitiesUser struct {
	Id               int32                        `json:"id,omitempty"`
	Username         string                       `json:"username,omitempty"`
	Name             string                       `json:"name,omitempty"`
	State            string                       `json:"state,omitempty"`
	Locked           bool                         `json:"locked,omitempty"`
	AvatarUrl        string                       `json:"avatar_url,omitempty"`
	AvatarPath       string                       `json:"avatar_path,omitempty"`
	CustomAttributes []ApiEntitiesCustomAttribute `json:"custom_attributes,omitempty"`
	WebUrl           string                       `json:"web_url,omitempty"`
	CreatedAt        string                       `json:"created_at,omitempty"`
	Bio              string                       `json:"bio,omitempty"`
	Location         string                       `json:"location,omitempty"`
	PublicEmail      string                       `json:"public_email,omitempty"`
	Skype            string                       `json:"skype,omitempty"`
	Linkedin         string                       `json:"linkedin,omitempty"`
	Twitter          string                       `json:"twitter,omitempty"`
	Discord          string                       `json:"discord,omitempty"`
	WebsiteUrl       string                       `json:"website_url,omitempty"`
	Organization     string                       `json:"organization,omitempty"`
	JobTitle         string                       `json:"job_title,omitempty"`
	Pronouns         string                       `json:"pronouns,omitempty"`
	Bot              string                       `json:"bot,omitempty"`
	WorkInformation  string                       `json:"work_information,omitempty"`
	Followers        string                       `json:"followers,omitempty"`
	Following        string                       `json:"following,omitempty"`
	IsFollowed       string                       `json:"is_followed,omitempty"`
	LocalTime        string                       `json:"local_time,omitempty"`
}
