/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Create an agent token
type PostApiV4ProjectsIdClusterAgentsAgentIdTokens struct {
	// The name for the token
	Name string `json:"name"`
	// The description for the token
	Description string `json:"description,omitempty"`
}
