/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Fork new project for the current user or provided namespace.
type PostApiV4ProjectsIdFork struct {
	// (deprecated) The ID or name of the namespace that the project will be forked into
	Namespace string `json:"namespace,omitempty"`
	// The ID of the namespace that the project will be forked into
	NamespaceId int32 `json:"namespace_id,omitempty"`
	// The path of the namespace that the project will be forked into
	NamespacePath string `json:"namespace_path,omitempty"`
	// The path that will be assigned to the fork
	Path string `json:"path,omitempty"`
	// The name that will be assigned to the fork
	Name string `json:"name,omitempty"`
	// The description that will be assigned to the fork
	Description string `json:"description,omitempty"`
	// The visibility of the fork
	Visibility string `json:"visibility,omitempty"`
	// Merge requests of this forked project targets itself by default
	MrDefaultTargetSelf bool `json:"mr_default_target_self,omitempty"`
	// Branches to fork
	Branches string `json:"branches,omitempty"`
}
