/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Transfer a project to a new namespace
type PutApiV4ProjectsIdTransfer struct {
	// The ID or path of the new namespace
	Namespace string `json:"namespace"`
}
