/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Trigger a slash command for slack-slash-commands
type PostApiV4ProjectsIdIntegrationsSlackSlashCommandsTrigger struct {
	// The Slack token.
	Token string `json:"token"`
}
