/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Enable a runner in project
type PostApiV4ProjectsIdRunners struct {
	// The ID of a runner
	RunnerId int32 `json:"runner_id"`
}
