/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// API_Entities_ProjectDailyStatistics model
type ApiEntitiesProjectDailyStatistics struct {
	Fetches *ApiEntitiesProjectDailyStatisticsFetches `json:"fetches,omitempty"`
}
