/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Set a custom attribute on a project
type PutApiV4ProjectsIdCustomAttributesKey struct {
	// The value of the custom attribute
	Value string `json:"value"`
}
