/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// API_Entities_Projects_Topic model
type ApiEntitiesProjectsTopic struct {
	Id                 string `json:"id,omitempty"`
	Name               string `json:"name,omitempty"`
	Title              string `json:"title,omitempty"`
	Description        string `json:"description,omitempty"`
	TotalProjectsCount string `json:"total_projects_count,omitempty"`
	AvatarUrl          string `json:"avatar_url,omitempty"`
}
