/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Set a url variable
type PutApiV4ProjectsIdHooksHookIdUrlVariablesKey struct {
	// The value of the variable
	Value string `json:"value"`
}
