/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// Generates a changelog section for a release and commits it in a changelog file
type PostApiV4ProjectsIdRepositoryChangelog struct {
	// The version of the release, using the semantic versioning format
	Version string `json:"version"`
	// The first commit in the range of commits to use for the changelog
	From string `json:"from,omitempty"`
	// The last commit in the range of commits to use for the changelog
	To string `json:"to,omitempty"`
	// The date and time of the release
	Date time.Time `json:"date,omitempty"`
	// The Git trailer to use for determining if commits are to be included in the changelog
	Trailer string `json:"trailer,omitempty"`
	// The branch to commit the changelog changes to
	Branch string `json:"branch,omitempty"`
	// The file path to the configuration file as stored in the project's Git repository. Defaults to '.gitlab/changelog_config.yml'
	ConfigFile string `json:"config_file,omitempty"`
	// The file to commit the changelog changes to
	File string `json:"file,omitempty"`
	// The commit message to use when committing the changelog
	Message string `json:"message,omitempty"`
}
