/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"os"
)

// Upload a chart
type PostApiV4ProjectsIdPackagesHelmApiChannelCharts struct {
	// The chart file to be published (generated by Multipart middleware)
	Chart **os.File `json:"chart"`
}
