/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ApiEntitiesPackageVersion struct {
	Id        string                      `json:"id,omitempty"`
	Version   string                      `json:"version,omitempty"`
	CreatedAt string                      `json:"created_at,omitempty"`
	Tags      string                      `json:"tags,omitempty"`
	Pipeline  *ApiEntitiesPackagePipeline `json:"pipeline,omitempty"`
}
