/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// API_Entities_ProjectExportStatus model
type ApiEntitiesProjectExportStatus struct {
	Id                int32                                `json:"id,omitempty"`
	Description       string                               `json:"description,omitempty"`
	Name              string                               `json:"name,omitempty"`
	NameWithNamespace string                               `json:"name_with_namespace,omitempty"`
	Path              string                               `json:"path,omitempty"`
	PathWithNamespace string                               `json:"path_with_namespace,omitempty"`
	CreatedAt         time.Time                            `json:"created_at,omitempty"`
	ExportStatus      string                               `json:"export_status,omitempty"`
	Links             *ApiEntitiesProjectExportStatusLinks `json:"_links,omitempty"`
}
