/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// ProjectEntity model
type ProjectEntity struct {
	Id       int32  `json:"id,omitempty"`
	Name     string `json:"name,omitempty"`
	FullPath string `json:"full_path,omitempty"`
	FullName string `json:"full_name,omitempty"`
	RefsUrl  string `json:"refs_url,omitempty"`
}
