/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Update an existing variable from a project
type PutApiV4ProjectsIdVariablesKey struct {
	// The value of a variable
	Value string `json:"value,omitempty"`
	// Whether the variable is protected
	Protected bool `json:"protected,omitempty"`
	// Whether the variable is masked
	Masked bool `json:"masked,omitempty"`
	// The environment_scope of a variable
	EnvironmentScope string `json:"environment_scope,omitempty"`
	// Whether the variable will be expanded
	Raw bool `json:"raw,omitempty"`
	// The type of the variable. Default: env_var
	VariableType string                                `json:"variable_type,omitempty"`
	Filter       *PutApiV4ProjectsIdVariablesKeyFilter `json:"filter,omitempty"`
	// The description of the variable
	Description string `json:"description,omitempty"`
}
