/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Create/Edit External Wiki integration
type PutApiV4ProjectsIdServicesExternalWiki struct {
	// URL of the external wiki.
	ExternalWikiUrl string `json:"external_wiki_url"`
}
