/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Update a release
type PutApiV4ProjectsIdReleasesTagName struct {
	// The release name
	Name string `json:"name,omitempty"`
	// The description of the release. You can use Markdown
	Description string `json:"description,omitempty"`
	// The date when the release is/was ready. Expected in ISO 8601 format (`2019-03-15T08:00:00Z`)
	ReleasedAt time.Time `json:"released_at,omitempty"`
	// The title of each milestone to associate with the release. GitLab Premium customers can specify group milestones. Cannot be combined with `milestone_ids` parameter. To remove all milestones from the release, specify `[]`
	Milestones []string `json:"milestones,omitempty"`
	// The ID of each milestone the release is associated with. GitLab Premium customers can specify group milestones. Cannot be combined with `milestones` parameter. To remove all milestones from the release, specify `[]`
	MilestoneIds string `json:"milestone_ids,omitempty"`
}
