/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// API_Entities_ProtectedBranch model
type ApiEntitiesProtectedBranch struct {
	Id                        int32                           `json:"id,omitempty"`
	Name                      string                          `json:"name,omitempty"`
	PushAccessLevels          []ApiEntitiesProtectedRefAccess `json:"push_access_levels,omitempty"`
	MergeAccessLevels         []ApiEntitiesProtectedRefAccess `json:"merge_access_levels,omitempty"`
	AllowForcePush            bool                            `json:"allow_force_push,omitempty"`
	UnprotectAccessLevels     []ApiEntitiesProtectedRefAccess `json:"unprotect_access_levels,omitempty"`
	CodeOwnerApprovalRequired bool                            `json:"code_owner_approval_required,omitempty"`
	Inherited                 bool                            `json:"inherited,omitempty"`
}
