/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"os"
)

// Create a new pages domain
type PostApiV4ProjectsIdPagesDomains struct {
	// The domain
	Domain string `json:"domain"`
	// The certificate
	Certificate **os.File `json:"certificate,omitempty"`
	// The key
	Key **os.File `json:"key,omitempty"`
	// Enables automatic generation of SSL certificates issued by Let's Encrypt for custom domains.
	AutoSslEnabled          bool   `json:"auto_ssl_enabled,omitempty"`
	UserProvidedCertificate string `json:"user_provided_certificate,omitempty"`
	UserProvidedKey         string `json:"user_provided_key,omitempty"`
}
