/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Create a deployment
type PostApiV4ProjectsIdDeployments struct {
	// The name of the environment to create the deployment for
	Environment string `json:"environment"`
	// The SHA of the commit that is deployed
	Sha string `json:"sha"`
	// The name of the branch or tag that is deployed
	Ref string `json:"ref"`
	// A boolean that indicates if the deployed ref is a tag (`true`) or not (`false`)
	Tag bool `json:"tag"`
	// The status of the deployment that is created. One of `running`, `success`, `failed`, or `canceled`
	Status string `json:"status"`
}
