/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Posts the current node status to the primary site
type PostApiV4GeoStatus struct {
	Data *PostApiV4GeoStatusData `json:"data,omitempty"`
}
