/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// API_Entities_FreezePeriod model
type ApiEntitiesFreezePeriod struct {
	Id           int32     `json:"id,omitempty"`
	FreezeStart  string    `json:"freeze_start,omitempty"`
	FreezeEnd    string    `json:"freeze_end,omitempty"`
	CronTimezone string    `json:"cron_timezone,omitempty"`
	CreatedAt    time.Time `json:"created_at,omitempty"`
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
}
