/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Update existing file in repository
type PutApiV4ProjectsIdRepositoryFilesFilePath struct {
	// Name of the branch to commit into. To create a new branch, also provide `start_branch`.
	Branch string `json:"branch"`
	// Commit message
	CommitMessage string `json:"commit_message"`
	// Name of the branch to start the new commit from
	StartBranch string `json:"start_branch,omitempty"`
	// The email of the author
	AuthorEmail string `json:"author_email,omitempty"`
	// The name of the author
	AuthorName string `json:"author_name,omitempty"`
	// File content
	Content string `json:"content"`
	// File encoding
	Encoding string `json:"encoding,omitempty"`
	// Last known commit id for this file
	LastCommitId string `json:"last_commit_id,omitempty"`
	// Enable / Disable the executable flag on the file path
	ExecuteFilemode bool `json:"execute_filemode,omitempty"`
}
