/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// API_Entities_ErrorTracking_ClientKey model
type ApiEntitiesErrorTrackingClientKey struct {
	Id        int32  `json:"id,omitempty"`
	Active    bool   `json:"active,omitempty"`
	PublicKey string `json:"public_key,omitempty"`
	SentryDsn string `json:"sentry_dsn,omitempty"`
}
