/*
 * GitLab API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Create/Edit Slack Slash Commands integration
type PutApiV4ProjectsIdIntegrationsSlackSlashCommands struct {
	// The Slack token
	Token string `json:"token"`
}
